# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go mod tidy
      run: go mod tidy
      
    - name: Go mod vendor
      run: go mod vendor

    - name: Create config.ts file
      working-directory: actionsTest
      run: echo "${{ secrets.CONFIG_TOML }}" > config.toml

    - name: cat
      working-directory: actionsTest
      run: cat config.toml

    - name: Build and run
      working-directory: actionsTest
      run: go run main.go
